
public class Exceptions {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		  try {
		         int a[] = new int[2];
		         System.out.println("Access element three :" + a[3]);
		      }catch(ArrayIndexOutOfBoundsException e) {
		         System.out.println("Exception thrown  :" + e);
		      }
		  finally {
		        // a[0] = 6;
		         System.out.println("First element value: ");
		         System.out.println("The finally statement is executed");
		      }
		  System.out.println("Out of the block");
//

		
		
		
		
		
		
		
		
		
	}

}
